### ISSUE TITLE
Chaining Problemi

### ISSUE THREAD

**Issue by omergulcicek** [bcinarli/uxr#4]
`addClass`, `removeClass`, `toggleClass`, `data`, `attr` (_farkettiklerim_) gibi metotlardan sonra chaining yapılamıyor.

**Comment by bcinarli** [comment]
Tasarim tercihi olara `data` ve `attr` genel anlamda _setter_, _getter_ mantigiyla calisiyor. O yuzden bu iki method `uxr` objesi yerine, sonucu donuyorlar. Dolayisiyla chaining bu ikisinde desteklenmiyor. Class metodlarinda bir problem varmis, o duzeltildi
